language: java
jdk:
  - openjdk8
  - openjdk11
sudo: enabled
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE employeebugs;'
  - sudo mysql < "employeebugs.sql"
script: mvn clean install